### PR TITLE
Upgrade urfave/cli and make register's config flag required

### PR DESCRIPTION
**Pull request by mauromorales**
With the upgrade of the cli pkg, making flags required is very simple, it just needs an attribute `required: true`

Fixes https://github.com/kairos-io/kairos/issues/375

:warning: breaking UX change

> In v2 flags must come before args. This is more POSIX-compliant. You may need to update scripts, user documentation, etc.

This means that 

```
provier-kairos command ARG FLAG
```

is no longer valid, but I still think the change is worth it because like the documentation says, the CLI will be more POSIX-compliant

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Looks good!

**Comment by mudler** [comment]
please fmt files, seems Linting is failing

**Comment by mudler** [comment]
We might need to check out if this is called somewhere in our tests, I think the UX changes might impact both docs and tests

**Comment by mauromorales** [comment]
> please fmt files, seems Linting is failing

sorry about that, I'm auto formatting on save, but I was using goimports and this required gofmt with simplification. I have changed my config to do that in the future. Should be good now :+1:

**Comment by mauromorales** [comment]
> We might need to check out if this is called somewhere in our tests, I think the UX changes might impact both docs and tests

ok, will follow up and get back to you

**Comment by mauromorales** [comment]
@mudler for what I can tell, there's no impact in the docs or tests (ran them locally with `earthly.sh +test` and `earhtly.sh +all`)

**Pull request merged**
