### PR TITLE
:robot: Push arm images in their own repo with img suffix

### PR DESCRIPTION
**Pull request by mauromorales**
relates to kairos-io/kairos#770

### CODE REVIEW

**Review by mudler — COMMENTED** [review]
:+1:

**Review by mudler — APPROVED** [review]

**Comment by mudler** [comment]
argh, post-mortem, we need to change it here actually: https://github.com/kairos-io/provider-kairos/blob/560fc4da0729426dd95df36c213e87bac2832e9b/.github/workflows/release-arm.yaml#L87

**Comment by mudler** [comment]
(and master too)

**Comment by mauromorales** [comment]
@mudler my bad, I thought it would be better changin `IMAGE` since `cat build/IMAGE` contains the tag `ARG IMAGE=quay.io/kairos/${VARIANT}-${FLAVOR}:$TAG`

https://github.com/kairos-io/provider-kairos/blob/560fc4da0729426dd95df36c213e87bac2832e9b/.github/workflows/release-arm.yaml#LL83C11-L83C37

https://github.com/kairos-io/provider-kairos/blob/main/Earthfile#L19

**Pull request merged**
